Pandas represents panel-data and python-data-analysis, from its name we can see that the basic objects of pandas are data series and data frame.

It's like a key-value based data table.

Pandas is based on NumPy, it's value of the series and dataframe are all numpy objects, once we are familiar with numpy, some pandas operation can be very easy.

Pandas is widely used in financial data analysis.

Today we are going to cover those topics:



1. Pandas basic data structure:
    

    *   Series
    *   DataFrame


2. Basic pandas functions

3. Scientific computing

In [0]:
import pandas as pd
from pandas import Series, DataFrame

In [3]:
!pip install tushare

Collecting tushare
  Downloading https://files.pythonhosted.org/packages/22/3a/0c49f17f76057aa68018564304ec5bda23183fdfc4c73ba712b8d8983938/tushare-1.2.40.tar.gz (168kB)
     |████████████████████████████████| 174kB 4.8MB/s
Requirement already satisfied: pandas>=0.18.0 in /usr/local/lib/python3.6/dist-packages (from tushare) (0.24.2)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from tushare) (2.21.0)
Requirement already satisfied: lxml>=3.8.0 in /usr/local/lib/python3.6/dist-packages (from tushare) (4.2.6)
Collecting simplejson>=3.16.0 (from tushare)
  Downloading https://files.pythonhosted.org/packages/e3/24/c35fb1c1c315fc0fffe61ea00d3f88e85469004713dab488dee4f35b0aff/simplejson-3.16.0.tar.gz (81kB)
     |████████████████████████████████| 81kB 22.9MB/s
Requirement already satisfied: bs4>=0.0.1 in /usr/local/lib/python3.6/dist-packages (from tushare) (0.0.1)
Requirement already satisfied: pytz>=2011k in /usr/local/lib/python3.6/dist-packages (from pandas>=0.18.0->tushare) (2018.9)
Requirement already satisfied: python-dateutil>=2.5.0 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.18.0->tushare) (2.5.3)
Requirement already satisfied: numpy>=1.12.0 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.18.0->tushare) (1.16.4)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests>=2.0.0->tushare) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests>=2.0.0->tushare) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=2.0.0->tushare) (2019.6.16)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests>=2.0.0->tushare) (1.24.3)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.6/dist-packages (from bs4>=0.0.1->tushare) (4.6.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil>=2.5.0->pandas>=0.18.0->tushare) (1.12.0)
Building wheels for collected packages: tushare, simplejson
  Building wheel for tushare (setup.py) ... done
  Created wheel for tushare: filename=tushare-1.2.40-cp36-none-any.whl size=210856 sha256=e495053067a503b65b25610221cc59f88747a460ebaaa3e6fe83dc4e2b8125a4
  Stored in directory: /root/.cache/pip/wheels/ec/04/42/ffd673dcf69f408fb7fa3600881b8e8f0b6a386890bad4d98f
  Building wheel for simplejson (setup.py) ... done
  Created wheel for simplejson: filename=simplejson-3.16.0-cp36-cp36m-linux_x86_64.whl size=114015 sha256=14b6c54a9bab3bd0dffaab72dc09643e1487317a1575090635e897a0d99b6455
  Stored in directory: /root/.cache/pip/wheels/5d/1a/1e/0350bb3df3e74215cd91325344cc86c2c691f5306eb4d22c77
Successfully built tushare simplejson
Installing collected packages: simplejson, tushare
Successfully installed simplejson-3.16.0 tushare-1.2.40

In [0]:
import numpy as np
from numpy.random import randn
import os
import matplotlib.pyplot as plt
import os
np.random.seed(42)
plt.rc('figure',figsize = (10,6))
np.set_printoptions(precision = 4)

Pandas series is like 1-dim data list, based on value and its corresponding index

In [6]:
se = Series([1,2,3,4])
print(se)
print(type(se))

0    1
1    2
2    3
3    4
dtype: int64
<class 'pandas.core.series.Series'>

In [7]:
se_np = Series(np.array([1,2,3,4]))
se_np

0    1
1    2
2    3
3    4
dtype: int64

In [9]:
print(se.values)
print(se.index)

[1 2 3 4]
RangeIndex(start=0, stop=4, step=1)

In [12]:
print(type(se.values))

<class 'numpy.ndarray'>

In [13]:
se2 = Series({'a':1,'b':2})
se2

a    1
b    2
dtype: int64

In [14]:
print(se2.values)
print(se2.index)

[1 2]
Index(['a', 'b'], dtype='object')

In [15]:
## Pass in an numpy array to construct the series
se3 = Series(np.array([1,2,3,4]), index = ['a','b','c','d'])
se3

a    1
b    2
c    3
d    4
dtype: int64

In [16]:
## Pass in a python list to construct the series
se4 = Series([1,2,3,4], index = ['a','b','c','d'])
se4

a    1
b    2
c    3
d    4
dtype: int64

Visiting :

In [0]:
## We can visit the value by its index
se4['a']

1

In [0]:
se4[['a','b']]

a    1
b    2
dtype: int64

In [0]:
ind = ['a', 'b']
se4[ind]

a    1
b    2
dtype: int64

Apply numpy functions on pandas series:

In [0]:
np.exp(se4)

a     2.718282
b     7.389056
c    20.085537
d    54.598150
dtype: float64

In [0]:
se4 + se3

a    2
b    4
c    6
d    8
dtype: int64

In [0]:
se4 + np.array([1,2,3,4])

a    2
b    4
c    6
d    8
dtype: int64

can also sum by scala

In [0]:
se4 + 2

a    3
b    4
c    5
d    6
dtype: int64

Get the value by using boolean:

In [0]:
se4[se4%2 == 0]

b    2
d    4
dtype: int64

In [0]:
2 in se4.values

True

In [0]:
10 in se4.values

False

The 'in' operation only effective for index, not value:

In [0]:
2 in se4

False

In [0]:
'a' in se4

True

The most intuitive way is using python dictionary to construct the Series:

In [0]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [0]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [0]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

select the row with NaN values

In [0]:
obj4[pd.isnull(obj4)]

California   NaN
dtype: float64

Series will automatically calculated based on index :

In [0]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [0]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [0]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

We can change index by assigning values:

In [0]:
se

0    1
1    2
2    3
3    4
dtype: int64

In [0]:
se.index = ['Jason','Schwartz','Katie','Flood']
se

Jason       1
Schwartz    2
Katie       3
Flood       4
dtype: int64

In [0]:
se

Jason       1
Schwartz    2
Katie       3
Flood       4
dtype: int64

DataFrame

Dataframe is a table like datastructure, it contains a whole series of columns, each column can be different data type (numerical, string, boolean, etc.)

Dataframe has both column and row index, it can be seen as dictionary based on Series. (with same indexing)

The most common way to build DataFrame is to pass in a dictionary

In [0]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)
print(frame.iloc[1],'\n')
print(frame.index,'\n')
frame

state    Ohio
year     2001
pop       1.7
Name: 1, dtype: object

RangeIndex(start=0, stop=5, step=1)

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

Re-order the columns:

In [0]:
DataFrame(data, columns=['year', 'state', 'pop'])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

If the data does not exist, there would be NA:

In [0]:

frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                   index=['one', 'two', 'three', 'four', 'five'])
frame2

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

By referencing a column, we can get a Series:

In [0]:
print(frame2['state'])

print(frame2.state)
print('\n',type(frame2.debt))
print('\n',type(frame2.iloc[0]))
print('\n',type(frame2.loc['four']))
print('\n',frame2.loc['four'])
print('\n',type(frame2['year']))
print('\n',frame2['year'])

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object
one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

 <class 'pandas.core.series.Series'>

 <class 'pandas.core.series.Series'>

 <class 'pandas.core.series.Series'>

 year       2001
state    Nevada
pop         2.4
debt        NaN
Name: four, dtype: object

 <class 'pandas.core.series.Series'>

 one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

How to get the row? using .iloc[number] or loc[index] method

In [0]:
frame2.iloc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: two, dtype: object

In [0]:
frame2.loc['two']

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: two, dtype: object

In [0]:
frame2.iloc[1] == frame2.loc['two']

year      True
state     True
pop       True
debt     False
Name: two, dtype: bool

In [0]:
frame2['debt'] = [1,2,3,4,4]
print(frame2['debt']['one'])
frame2

1

       year   state  pop  debt
one    2000    Ohio  1.5     1
two    2001    Ohio  1.7     2
three  2002    Ohio  3.6     3
four   2001  Nevada  2.4     4
five   2002  Nevada  2.9     4

Use list or np.array to assign value, need to match the length of the DataFrame

In [0]:
frame2['debt'] = np.arange(5.)
print(type(frame2.values))
frame2.values

<class 'numpy.ndarray'>

array([[2000, 'Ohio', 1.5, 0.0],
       [2001, 'Ohio', 1.7, 1.0],
       [2002, 'Ohio', 3.6, 2.0],
       [2001, 'Nevada', 2.4, 3.0],
       [2002, 'Nevada', 2.9, 4.0]], dtype=object)

If you assign a Series,  the assignment will be finished with matching the index

In [0]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
print(frame2)

print(frame2.values)

       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
[[2000 'Ohio' 1.5 nan]
 [2001 'Ohio' 1.7 -1.2]
 [2002 'Ohio' 3.6 nan]
 [2001 'Nevada' 2.4 -1.5]
 [2002 'Nevada' 2.9 -1.7]]

In [0]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

       year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [0]:
del frame2['eastern']
frame2

       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

When passing dictionary as the argument for DataFrame, the out layer is the column, and the inner layer is the row index

In [0]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = DataFrame(pop)
frame3

      Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

We can also transpose a dataframe:

In [0]:
frame3.T

        2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

The value of dataframe is ndarray:

In [0]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [0]:
print(frame2.values)
print(type(frame2.values))

[[2000 'Ohio' 1.5 nan]
 [2001 'Ohio' 1.7 -1.2]
 [2002 'Ohio' 3.6 nan]
 [2001 'Nevada' 2.4 -1.5]
 [2002 'Nevada' 2.9 -1.7]]
<class 'numpy.ndarray'>

We can also assign value for the DataFrame directly for generation:

In [0]:
frame4=DataFrame(np.array([[0, 1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]]),index=['2001','2002','2003'],columns=['Nevada','Ohio'])
frame4

      Nevada  Ohio
2001     0.0   1.5
2002     2.4   1.7
2003     2.9   3.6

Drop a row:

In [0]:
obj = Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
print(obj)

obj.drop(['d', 'c'])

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

a    0.0
b    1.0
e    4.0
dtype: float64

If specify that axis=1, will delete the column:

In [0]:
data = DataFrame(np.arange(16).reshape((4, 4)),
                 index=['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns=['one', 'two', 'three', 'four'])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [0]:
data = data.drop(['Ohio', 'Colorado'])
data.drop(['two','four'],axis=1)

          one  three
Utah        8     10
New York   12     14

Indexing, selection and filtering:


*   Series can use index, int, boolean for selection
*   DataFrame's indexing can get one or several columns
*   If want to manipulate row, need to use iloc

In [0]:
obj = Series(np.arange(4.0), index=['a', 'b', 'c', 'd'])
print(obj.dtype)

print(obj['b']) # index
print(obj[['b', 'a', 'd']])

float64
1.0
b    1.0
a    0.0
d    3.0
dtype: float64

In [0]:
## by using int or list
print(obj[1])
print(obj[1:3])
print(obj[[1,3]])
print(obj[['b', 'd']])

1.0
b    1.0
c    2.0
dtype: float64
b    1.0
d    3.0
dtype: float64
b    1.0
d    3.0
dtype: float64

In [0]:
obj[[True,False,False,False]]

a    0.0
dtype: float64

In [0]:
print(obj<2)
print(obj[obj<2])

a     True
b     True
c    False
d    False
dtype: bool
a    0.0
b    1.0
dtype: float64

In [0]:
data = DataFrame(np.arange(16).reshape((4, 4)),
                 index=['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns=['one', 'two', 'three', 'four'])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [0]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [0]:
data.iloc[0]

one      0
two      1
three    2
four     3
Name: Ohio, dtype: int64

In [0]:
data.loc['Ohio']

one      0
two      1
three    2
four     3
Name: Ohio, dtype: int64

In [0]:
data.loc['Ohio':]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [0]:
data.loc['Utah':]

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [0]:
data.loc[:'Utah']

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11

In [0]:
data[1:]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [0]:
data.iloc[1:]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [0]:
data>5

            one    two  three   four
Ohio      False  False  False  False
Colorado  False  False   True   True
Utah       True   True   True   True
New York   True   True   True   True

In [0]:
data[data>5]

           one   two  three  four
Ohio       NaN   NaN    NaN   NaN
Colorado   NaN   NaN    6.0   7.0
Utah       8.0   9.0   10.0  11.0
New York  12.0  13.0   14.0  15.0

In [0]:
data.loc[['Colorado','Utah']]['one']

Colorado    4
Utah        8
Name: one, dtype: int64

In [0]:
data.ix[data.three > 5, :2]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

          one  two
Colorado    4    5
Utah        8    9
New York   12   13

In [0]:
data2=data.ix[['Colorado', 'Utah'], [3, 0, 1]]
 
data3=data.ix[data.three > 5, :2] 

print(data)
print(data2)
print(data3)

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
          four  one  two
Colorado     7    4    5
Utah        11    8    9
          one  two
Colorado    4    5
Utah        8    9
New York   12   13

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  This is separate from the ipykernel package so we can avoid doing imports until

Calculation:
The basic idea is to calculate based on index.

In [0]:
s1 = Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])
s1 * s2

a   -15.33
c    -9.00
d      NaN
e    -2.25
f      NaN
g      NaN
dtype: float64

In [0]:
df1 = DataFrame(np.arange(9.).reshape((3, 3)), columns=['as','xi','ba'],
                index=['Ohio', 'Texas', 'Colorado'])

print(df1)
df2 = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                index=['Utah', 'Ohio', 'Texas', 'Oregon'])
print(df2)
print(df1 + df2)

           as   xi   ba
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0
          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
          as   b  ba   d   e  xi
Colorado NaN NaN NaN NaN NaN NaN
Ohio     NaN NaN NaN NaN NaN NaN
Oregon   NaN NaN NaN NaN NaN NaN
Texas    NaN NaN NaN NaN NaN NaN
Utah     NaN NaN NaN NaN NaN NaN

Fill NA:

In [0]:
df1 = DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df2 = DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))
#dfadd=df1+df2
dfaddfill0=df1.add(df2, fill_value=0)
print(df1)
print(df2)
print(dfaddfill0)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0
      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

DataFrame vs Series:

In [0]:
arr = np.arange(12.).reshape((3, 4))
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [0]:
arr - arr[1]

array([[-4., -4., -4., -4.],
       [ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.]])

In [0]:
frame = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.ix[0]
fsubr=frame - series
print(frame)
print(fsubr)

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  This is separate from the ipykernel package so we can avoid doing imports until

In [0]:
series2 = Series(range(3), index=['b', 'e', 'f'])
frame + series2

          b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

Broadcast: by default is by row, if you want to broadcast by columns, you need to claim that axis=0

In [0]:
series3 = frame['d']
fsubc=frame.sub(series3, axis=0)
print(frame)
print(fsubc)

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
          b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

numpy functions can also be applied to dataframe:

In [0]:
frame = DataFrame(np.random.randn(4, 3), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])
fabs=np.abs(frame)

In [0]:
frame

               b         d         e
Utah    0.496714 -0.138264  0.647689
Ohio    1.523030 -0.234153 -0.234137
Texas   1.579213  0.767435 -0.469474
Oregon  0.542560 -0.463418 -0.465730

In [0]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    1.082499
d    1.230852
e    1.117163
dtype: float64

In [0]:
frame

               b         d         e
Utah    0.496714 -0.138264  0.647689
Ohio    1.523030 -0.234153 -0.234137
Texas   1.579213  0.767435 -0.469474
Oregon  0.542560 -0.463418 -0.465730

In [0]:
frame.apply(f,axis=1)

Utah      0.785953
Ohio      1.757183
Texas     2.048687
Oregon    1.008290
dtype: float64

In [0]:
## When return value has multiple dims
def nf(x):
    return Series([x.min(), x.max()], index=['min','max'])
frame.apply(nf)

            b         d         e
min  0.496714 -0.463418 -0.469474
max  1.579213  0.767435  0.647689

In [0]:
## elementwise function
frame.apply(np.exp)

               b         d         e
Utah    1.643313  0.870868  1.911118
Ohio    4.586099  0.791240  0.791253
Texas   4.851136  2.154233  0.625331
Oregon  1.720406  0.629130  0.627677

Order:


1.   Ordering based on keyword, using sort_index
2.   When soring the dataframe, by default we will sort wrt rows, if want to operate on columns, need to claim that axis = 1
3.   accending = True or False to control the order
4.    If want to sort based on values of Series, need to use sort_values. Missing data will be appended to the end
5.    To sort the DataFrame's value, need to pass value by the column name

In [0]:
obj = Series(np.arange(4), index = ['a','c','d','b'])
obj.sort_index()

a    0
b    3
c    1
d    2
dtype: int64

In [0]:
obj.sort_values()

a    0
c    1
d    2
b    3
dtype: int64

In [0]:
frame = DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'],
                  columns=['d', 'a', 'b', 'c'])
frame.sort_index()

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [0]:
frame.sort_values(by='a')

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [0]:
frame.sort_values(by='a',ascending=False)

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [0]:
obj = Series([5,1,7,2,np.nan, 23,57,np.nan])
obj.sort_values()

1     1.0
3     2.0
0     5.0
2     7.0
5    23.0
6    57.0
4     NaN
7     NaN
dtype: float64

In [0]:
obj = Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [0]:
obj.rank(ascending = False, method = 'max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [0]:
frame = DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                   'c': [-2, 5, 8, -2.5]})
print(frame)
print(frame.rank())

     b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5
     b    a    c
0  3.0  1.5  2.0
1  4.0  3.5  3.0
2  1.0  1.5  4.0
3  2.0  3.5  1.0

In [0]:
frame.rank(axis = 1)

     b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

Duplicated indices:

In [0]:
obj = Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [0]:
obj['a']

a    0
a    1
dtype: int64

In [0]:
df = DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

          0         1         2
a  0.241962 -1.913280 -1.724918
a -0.562288 -1.012831  0.314247
b -0.908024 -1.412304  1.465649
b -0.225776  0.067528 -1.424748

In [0]:
df.loc['a']

          0         1         2
a  0.241962 -1.913280 -1.724918
a -0.562288 -1.012831  0.314247

Some simple calculation:

In [0]:
df = DataFrame([[1.4, np.nan], [7.1, -4.5],
                [np.nan, np.nan], [0.75, -1.3]],
               index=['a', 'b', 'c', 'd'],
               columns=['one', 'two'])
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [0]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [0]:
df.sum(axis = 1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [0]:
df.mean(axis = 1, skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [0]:
df.idxmax()

one    b
two    d
dtype: object

In [0]:
df.cumsum()

    one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [0]:
df['one'].unique()

array([1.4 , 7.1 ,  nan, 0.75])

Data Merge:

pandas.merge will combine row by row, i.e. horizontally

pandas.concat will combine column by column, i.e. vertically

In [0]:
df1 = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                 'data1': range(7)})
df2 = DataFrame({'key': ['a', 'b','b', 'd'],
                 'data2': range(4)})
df3 = DataFrame({'key': ['a', 'b','b', 'd','e'],
                 'data2': range(5)})

print(df1)
print(df1.index)

print(df2)

print(df3)

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6
RangeIndex(start=0, stop=7, step=1)
  key  data2
0   a      0
1   b      1
2   b      2
3   d      3
  key  data2
0   a      0
1   b      1
2   b      2
3   d      3
4   e      4

If not specify based on which cretiria, pandas will use the overlapped column as the key and concat/merge based on that

pd.merge include different methods, like inner(default), left, right, outer

In [0]:
dfmerge1=pd.merge(df1, df2)
print (dfmerge1)

  key  data1  data2
0   b      0      1
1   b      0      2
2   b      1      1
3   b      1      2
4   b      6      1
5   b      6      2
6   a      2      0
7   a      4      0
8   a      5      0

In [0]:
dfmerge1=pd.merge(df1, df2,on='key')
dfmerge2=pd.merge(df1, df2, on='key',how="left")
dfmerge3=pd.merge(df1, df2, on='key',how="right")
dfmerge4=pd.merge(df1, df2, on='key',how="outer")
print(df1)
print(df2)
print(dfmerge1)
print(dfmerge2)
print(dfmerge3)
print(dfmerge4)

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6
  key  data2
0   a      0
1   b      1
2   b      2
3   d      3
  key  data1  data2
0   b      0      1
1   b      0      2
2   b      1      1
3   b      1      2
4   b      6      1
5   b      6      2
6   a      2      0
7   a      4      0
8   a      5      0
  key  data1  data2
0   b      0    1.0
1   b      0    2.0
2   b      1    1.0
3   b      1    2.0
4   a      2    0.0
5   c      3    NaN
6   a      4    0.0
7   a      5    0.0
8   b      6    1.0
9   b      6    2.0
  key  data1  data2
0   b    0.0      1
1   b    1.0      1
2   b    6.0      1
3   b    0.0      2
4   b    1.0      2
5   b    6.0      2
6   a    2.0      0
7   a    4.0      0
8   a    5.0      0
9   d    NaN      3
   key  data1  data2
0    b    0.0    1.0
1    b    0.0    2.0
2    b    1.0    1.0
3    b    1.0    2.0
4    b    6.0    1.0
5    b    6.0    2.0
6    a    2.0    0.0
7    a    4.0    0.0
8    a    5.0    0.0
9    c    3.0    NaN
10   d    NaN    3.0

If merge based on key, and we have duplicated keys:

In [0]:
df1 = DataFrame({'key': ['a', 'b'],
                 'data1': range(2)})
df2 = DataFrame({'key': ['b',  'b' ],
                 'data2': range(2)})
merge4=pd.merge(df1, df2, how='inner')
print(df1)
print(df2)
print(merge4)

  key  data1
0   a      0
1   b      1
  key  data2
0   b      0
1   b      1
  key  data1  data2
0   b      1      0
1   b      1      1

In [0]:
left = DataFrame({'代码': ['foo', 'foo', 'bar'],
                  'key2': ['one', 'two', 'one'],
                  'lval': [1, 2, 3]}) 
right = DataFrame({'代码': ['foo', 'foo', 'bar', 'bar'],
                   'key2': ['one', 'one', 'one', 'two'],
                   'rval': [4, 5, 6, 7]})
merge5=pd.merge(left, right, on='代码', how='outer')
merge6=pd.merge(left, right, on=['代码', 'key2'], how='inner')
print(left)
print(right)
print(merge5)
print(merge6)

    代码 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3
    代码 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7
    代码 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7
    代码 key2  lval  rval
0  foo  one     1     4
1  foo  one     1     5
2  bar  one     3     6

In [0]:
left1 = DataFrame({'代码': ['a', 'b', 'a', 'a', 'b', 'c'],
                  'value': range(6)})
right1 = DataFrame({'平均值': [3.5, 7]}, index=['a', 'b'])


pm2=pd.merge(left1, right1, left_on='代码', right_index=True)

In [0]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [0]:
np.concatenate([arr, arr], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [0]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [0]:
s1 = Series([0, 1], index=['a', 'b'])
s2 = Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = Series([5, 6], index=['c', 'g'])
s_all = pd.concat([s1, s2, s3])
print(s1)
print(s2)
print(s3)
print(s_all)

a    0
b    1
dtype: int64
c    2
d    3
e    4
dtype: int64
c    5
g    6
dtype: int64
a    0
b    1
c    2
d    3
e    4
c    5
g    6
dtype: int64

In [0]:
pd.concat([s1, s2, s3], axis=1)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

     0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  5.0
d  NaN  3.0  NaN
e  NaN  4.0  NaN
g  NaN  NaN  6.0

In [0]:
df1 = DataFrame(np.arange(6).reshape(3, 2), index=['a', 'b', 'c'],
                columns=['one', 'two'])
df2 = DataFrame(5 + np.arange(4).reshape(2, 2), index=['a', 'c'],
                columns=['three', 'four'])
cdf = pd.concat([df1, df2], axis=1)
print(df1)
print(df2)
print(cdf)

   one  two
a    0    1
b    2    3
c    4    5
   three  four
a      5     6
c      7     8
   one  two  three  four
a    0    1    5.0   6.0
b    2    3    NaN   NaN
c    4    5    7.0   8.0

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """

In [0]:
data = DataFrame({'k1': ['one'] * 3 + ['two'] * 4,
                  'k2': [1, 1, 2, 3, 3, 4, 4]})
newdata1=data.drop_duplicates()
print(data)
print(newdata1)

    k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4
    k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [0]:

data['v1'] = range(7)##data is a dataframe

newdata2=data.drop_duplicates(['k1'])
newdata3=data.drop_duplicates(['k1', 'k2'], keep='last')

print(data)
print(newdata2)
print(newdata3)

    k1  k2  v1
0  one   1   0
1  one   1   1
2  one   2   2
3  two   3   3
4  two   3   4
5  two   4   5
6  two   4   6
    k1  k2  v1
0  one   1   0
3  two   3   3
    k1  k2  v1
1  one   1   1
2  one   2   2
4  two   3   4
6  two   4   6

Group by:

In [0]:
df = DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
                'key2' : ['one', 'two', 'one', 'two', 'one'],
                'data1' : range(5),
                'data2' : range(5)})
grouped = df['data1'].groupby(df['key1'])##***groupby****
a = df.groupby('key1')

print(df) 
print(a.mean())
print(grouped.mean())

  key1 key2  data1  data2
0    a  one      0      0
1    a  two      1      1
2    b  one      2      2
3    b  two      3      3
4    a  one      4      4
         data1     data2
key1
a     1.666667  1.666667
b     2.500000  2.500000
key1
a    1.666667
b    2.500000
Name: data1, dtype: float64

In [0]:
means = df['data1'].groupby([df['key1'], df['key2']]).mean()##[[]]用法
print(means)

key1  key2
a     one     2
      two     1
b     one     2
      two     3
Name: data1, dtype: int64

In [0]:
means.unstack()

key2  one  two
key1
a       2    1
b       2    3

In [0]:
dfmeans = df.groupby(['key1', 'key2']).mean()
dfmeans.unstack()

     data1     data2
key2   one two   one two
key1
a        2   1     2   1
b        2   3     2   3

In [0]:
df.groupby([df['key1'], df['key2']])[['data2']].mean()

           data2
key1 key2
a    one       2
     two       1
b    one       2
     two       3

In [0]:
grouped = df.groupby('key1')
grouped['data1'].quantile(0.9)

key1
a    3.4
b    2.9
Name: data1, dtype: float64

In [0]:
def peak_to_peak(arr):
    return arr.max() - arr.min()
grouped.agg(peak_to_peak)

      data1  data2
key1
a         4      4
b         1      1

iterate grouped object

In [0]:
for name, group in grouped:
  print(name)
  print(group)

a
  key1 key2  data1  data2
0    a  one      0      0
1    a  two      1      1
4    a  one      4      4
b
  key1 key2  data1  data2
2    b  one      2      2
3    b  two      3      3